fix build errors
This patch fixes following build errors
when it doesn't support scaling feature.

error: use of undeclared identifier 'supported_lists'

Change-Id: If01b25a9844375034f178e69b050b00ac7fe0b5c
Signed-off-by: HyejungKwon <cjscld15@nexell.co.kr>